### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by acabal** [crvdgc/h-g-wells_the-world-set-free#1]
- [x] Prologue: h2 should have epub:type `title` and h3 should have epub:type `subtitle`
- [x] epub:type of sections in the prologue should be `chapter`
- [x] `id` of those sections should be simply `prologue-N`
- [x] Once all that is done run `se print-toc` again to output the correct ToC
- [x] Remove the word `Chapter` from headers in the actual chapters, and update the file titles and ToC
- [x] epub:type of sections in chapters should be `subchapter`
- [x] IDs of those sections should be `chapter-N-M`
- [x] Colophon: H. G. needs `<abbr class="name">`
- [x] Colophon: Titlecase the painting name using `se titlecase`
- [x] Dedication is missing the standard dedication CSS. See the manual
- [x] Dedication: Don't use two `<p>` tags here, just one is enough with `<br>`s and make sure to lowercase `This story`
- [x] Dedication: In print this is styled with small caps, you can do that with CSS
- [x] Remove italics from signature CSS, small caps is enough
- [x] Metadata short description: is `unites` better than `united`? Descriptions should always refer to books as in the present.
- [x] Metadata long description: This must be escaped HTML. See the manual.
- [x] Metadata long description typo: `the nuclear `
- [x] Can you flesh out the metadata long description more? Maybe a brief plot summary without spoilers? Any interesting publication history? The Wikipedia article as a lot of detail. But **don't copy and paste from Wikipedia**.

**Comment by crvdgc** [comment]
>  Prologue: h2 should have epub:type title and h3 should have epub:type subtitle

This will make the `<title>` to be `Prelude`, instead of `Prelude: The Sun Snares`, different from other chapters like `1: The New Source of Energy`, is that okay?

**Comment by acabal** [comment]
Yes, use whatever the output of `se print-title` is
